### ISSUE TITLE
Feature Request: Reading in parameters stored as a dictionary within yaml

### ISSUE THREAD

**Issue by erik-rosenstrom** [CDCgov/abc-calibration-tools#19]
**Is your feature request related to a problem? Please describe.**
A key set of calibration parameters in the GCM isolation model are the average contact rates by group. These are read into the model via a map (i.e., dictionary). Currently, there is no way to handle this parameter data structure when specifying calibration parameters in the pipeline. This will also be relevant when calibrating parameters within complex policies.

**Additional context**
An example of these parameters within the yaml is as follows.
```
baseScenario:
  population: 10000
  avgSchoolSize: 50
  avgHomeSize: 100
  avgWorkplaceSize: 100
  averageContactsPerDay:
    HOME: 0.5
    WORK: 0.25
    SCHOOL: 0.25
    COMMUNITY: 0.25
```
